export const themes = {
  korea: {
    title: "KOREA",
    logo: "korea.svg",
    primary_bg: "#73001C",
    secondary_bg: "#FFFFFF",
    title_color: "#FFFFFF",
    desc_color: "#73001C",
    border_color: "#FFFFFF",
  },
  soongsil: {
    title: "SOONGSIL",
    logo: "soongsil.svg",
    primary_bg: "#00B3FF",
    secondary_bg: "#FFFFFF",
    title_color: "#FFFFFF",
    desc_color: "#00B3FF",
    border_color: "#FFFFFF",
  },
  hanyang: {
    title: "HANYANG",
    logo: "hanyang.svg",
    primary_bg: "#006BCD",
    secondary_bg: "#FFFFFF",
    title_color: "#FFFFFF",
    desc_color: "#006BCD",
    border_color: "#FFFFFF",
  },
  sungkyunkwan: {
    title: "SUNGKYUN",
    logo: "sungkyunkwan.svg",
    primary_bg: "#003B71",
    secondary_bg: "#65B12F",
    title_color: "#FFFFFF",
    desc_color: "#FFFFFF",
    border_color: "#FFFFFF",
  },
};
